[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde = { version = "1.0.204", optional = true }
tracing = { version = "0.1.40", features = ["async-await"] }
slicedisplay = "0.2.2"
snafu = { version = "0.8.2", features = ["backtrace", "futures"] }
tsify-next = { version = "0.5.3", optional = true }
wasm-bindgen = { version = "0.2.92", optional = true }

[dev-dependencies]
pretty_assertions = "1.4.0"
tracing-test = "0.2.5"
criterion = { version = "0.5", features = ["html_reports","stable","async_tokio"] }

[features]
serde = ["dep:serde"]
wasm = [
    "dep:wasm-bindgen",
    "dep:tsify-next",
    "serde",
]
[[bench]]
name = "parser"
harness = false