[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.37.0", features = ["test-util", "tracing", "rt-multi-thread", "macros"] }
async-recursion = "1.1.0"
colored = "2.1.0"
clap = { version = "4.5.4", features = ["derive"] }
tracing = { version = "0.1.40", features = ["async-await"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
rustyline = "14.0.0"
futures = "0.3.30"

[lib]

[[bin]]
name = "RetiREPL"
path = "./src/main.rs"
