name: Rust

on:
  push:
    paths:
      - parser/**
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Building Parser
        run: cargo build --verbose
        working-directory: parser
