name: reti-ui-common

on:
  push:
    paths:
      - reti-ui-common/**
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "reti-ui-common/pnpm-lock.yaml"
      - name: Install dependencies
        run: pnpm install
        working-directory: reti-ui-common
      - name: Install wasm-bindgen
        run: cargo install -f wasm-bindgen-cli
        working-directory: reti-js
      - name: Check
        run: pnpm run check
        working-directory: reti-ui-common
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "reti-ui-common/pnpm-lock.yaml"
      - name: Install dependencies
        run: pnpm install
        working-directory: reti-ui-common
      - name: Install wasm-bindgen
        run: cargo install -f wasm-bindgen-cli
        working-directory: reti-js
      - name: Lint
        run: pnpm run lint
        working-directory: reti-ui-common
  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "reti-ui-common/pnpm-lock.yaml"
      - name: Install dependencies
        run: pnpm install
        working-directory: reti-ui-common
      - name: fmt check
        run: pnpm run fmt:check
        working-directory: reti-ui-common
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "reti-ui-common/pnpm-lock.yaml"
      - name: Install dependencies
        run: pnpm install
        working-directory: reti-ui-common
      - name: Install wasm-bindgen
        run: cargo install -f wasm-bindgen-cli
        working-directory: reti-js
      - name: Test
        run: pnpm run test
        working-directory: reti-ui-common
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "reti-ui-common/pnpm-lock.yaml"
      - name: Install dependencies
        run: pnpm install
        working-directory: reti-ui-common
      - name: Install wasm-bindgen
        run: cargo install -f wasm-bindgen-cli
        working-directory: reti-js
      - name: Build
        run: pnpm run build
        working-directory: reti-ui-common
