name: ui-common

on:
  push:
    paths:
      - web-packages/common/**
  pull_request:
    branches:
      - main
      - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Install wasm-bindgen
        uses: jetli/wasm-bindgen-action@v0.2.0
      - name: Check
        run: pnpm run check
        working-directory: web-packages/common
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Install wasm-bindgen
        uses: jetli/wasm-bindgen-action@v0.2.0
      - name: Test
        run: pnpm run test
        working-directory: web-packages/common
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Install wasm-bindgen
        uses: jetli/wasm-bindgen-action@v0.2.0
      - name: Build
        run: pnpm run build
        working-directory: web-packages/common
